services:
  api:
    build: ./backend
    image: blog-api
    networks:
      - api
      - db
    depends_on:
      - db
  nginx:
    build: ./frontend
    image: blog-nginx
    ports:
      - 80:80
    networks:
      - api
  db:
    build: ./database
    image: blog-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

volumes:
  db:

networks:
  api:
    driver: bridge
  db:
    driver: bridge
